---
application:
  name: "front-full"
  project: "web"
  organization: "QoveryCommunity"
routers:
- name: "main-front-full"
  custom_domains:
  - branch: master
    domain: zaza.qovery.fr
  routes:
  - application_name: "front-full"
    paths:
    - "/*"
