---
application:
  name: "front-full"
  project: "web"
  organization: "QoveryCommunity"
routers:
- name: "main-front-full"
  custom_domains:
  - branch: master
    domain: zozo.qovery.com
  routes:
  - application_name: "front-full"
    paths:
    - "/*"
