import React, { Fragment, useState } from 'react'
import { Graphic } from '../components/graphic/graphic'

const pop = [
    [
        [
            false,
            false,
            false
        ],
        [
            false,
            false,
            false
        ],
        [
            false,
            false,
            false
        ]
    ],
    [
        [
            false,
            false,
            false
        ],
        [
            false,
            false,
            false
        ],
        [
            false,
            false,
            false
        ]
    ],
    [
        [
            false,
            false,
            false
        ],
        [
            false,
            false,
            false
        ],
        [
            false,
            false,
            false
        ]
    ]
]

const pop2 = [
    [
        [
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false
        ]
    ],
    [
        [
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false
        ]
    ],
    [
        [
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false
        ]
    ],
    [
        [
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false
        ]
    ]
]

const pop3 = [
    [
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ]
    ],
    [
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ]
    ],
    [
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ]
    ],
    [
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ]
    ],
    [
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false
        ]
    ]
]
const Simulation = props => {
    const [day, setDay] = useState(0)

    return (
        <Fragment>
            <Graphic pop={pop} day={day} />
            <button onClick={() => { setDay(day + 1) }}> Click</button>
        </Fragment>
    )
}

export default Simulation